CREATE DATABASE INFORMATION;
SHOW DATABASES;
USE INFORMATION;

CREATE TABLE STUDENT
(
ID INTEGER PRIMARY KEY,
NAME VARCHAR(20),
DEPARTMENT VARCHAR(20)
);
SHOW TABLES;

SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUES(1, 'ASHWINI' , 'IT');
INSERT INTO STUDENT (ID, NAME, DEPARTMENT) VALUES (2, 'SHUBHAM', 'IT');
INSERT INTO STUDENT (ID, DEPARTMENT, NAME) VALUES (3, 'IT', 'KARTIK');

ALTER TABLE STUDENT ADD JOIN_DATE DATE;
ALTER TABLE STUDENT MODIFY NAME VARCHAR(30);
ALTER TABLE STUDENT RENAME TO STUD;
ALTER TABLE STUD RENAME TO STUDENT;
ALTER TABLE STUDENT DROP COLUMN JOIN_DATE;

TRUNCATE TABLE STUDENT;
TRUNCATE TABLE STUDENT;
DROP TABLE STUDENT;
RENAME TABLE STUDENT TO STUD;

INSERT INTO STUDENT VALUES (4 , 'VIKAS', 'COMPUTER');
INSERT INTO STUDENT VALUES(5, 'ALISHA' , 'COMPUTER');
DELETE FROM STUDENT WHERE ID=3;
DELETE FROM STUDENT WHERE ID=3;
SELECT NAME FROM STUDENT;
SELECT DEPARTMENT FROM STUDENT;
SELECT 1 FROM STUDENT;
SELECT 'NAME OF THE STUDENT IS' , NAME FROM STUDENT;

USE INFORMATION;
CREATE TABLE EMPLOYEE
(
EID INTEGER PRIMARY KEY,
ENAME VARCHAR(30),
EDEPARTMENT VARCHAR(30),
ESALARY INTEGER,
DEPTNO INTEGER
);
SELECT * FROM EMPLOYEE;
SELECT ESALARY+3000 AS "NEW_SAL" , ESALARY FROM EMPLOYEE;
SELECT ESALARY*12 AS "ANNUAL_SALARY" , ESALARY FROM EMPLOYEE;
SELECT (ESALARY+300)*12  AS " ANNUAL_SALARY_WITH_BONUS" , ESALARY FROM EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(1, 'SHUBHAM' , 'IT', 50000 , 10);
INSERT INTO EMPLOYEE VALUES(2, 'ASHWINI' , 'IT', 60000 , 10);
INSERT INTO EMPLOYEE VALUES(3, 'ANIKET' , 'IT', 70000 , 10);
INSERT INTO EMPLOYEE VALUES(4, 'PARTH' , 'IT', 50000 , 10);
INSERT INTO EMPLOYEE VALUES(5, 'VIKAS' , 'IT', 60000 , 10);
INSERT INTO EMPLOYEE VALUES(6, 'ANSHU' , 'IT', 70000 , 10);
INSERT INTO EMPLOYEE VALUES(7, 'MADHURI' , 'COMPUTER', 70000 , 10);

SELECT DISTINCT ESALARY FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE  ENAME='SHUBHAM';

SELECT * FROM EMPLOYEE WHERE EDEPARTMENT='COMPUTER';

SELECT * FROM EMPLOYEE WHERE EDEPARTMENT='IT';













